ALTER TABLE records
ADD COLUMN IF NOT EXISTS "referenciaCatastralPS" VARCHAR NULL;

ALTER TABLE records
ADD COLUMN IF NOT EXISTS "XPS" VARCHAR NULL;

ALTER TABLE records
ADD COLUMN IF NOT EXISTS "YPS" VARCHAR NULL;

ALTER TABLE records
ADD COLUMN IF NOT EXISTS "HusoPS" VARCHAR NULL;

ALTER TABLE records
ADD COLUMN IF NOT EXISTS "BandaPS" VARCHAR NULL;

ALTER TABLE records
ADD COLUMN IF NOT EXISTS "PaisPS" VARCHAR NULL;
