ALTER TABLE records
ADD COLUMN IF NOT EXISTS "desProvinciaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoMunicipioPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "desMunicipioPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "PoblacionPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "desPoblacionPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "tipoViaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "viaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "numFincaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "duplicadorFincaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "escaleraPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "pisoPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "puertaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "tipoAclaradorFincaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "aclaradorFincaPS" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoSegmentoCargoEnVigor" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "tipoControDelPotencia" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "cambioComercializadorEnCurso" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoComercializadorVigente" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "fechaUltimoCambioAgregadorIndependiente" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "cambioAgregadorIndependienteEnCurso" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoAgregadorIndependienteVigente" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "suspensionSuminstroImpago" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "tipoPersona" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "idTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "nombreTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "apellido1Titular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "apellido2Titular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "PaisTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoProvinciaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "desProvinciaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoMunicipioTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "desMunicipioTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "PoblacionTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "desPoblacionTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoPostalTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "tipoViaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "viaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "numFincaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "duplicadorFincaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "escaleraTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "pisoTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "puertaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "tipoAclaradorFincaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "aclaradorFincaTitular" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "codigoLecturaRemota" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "acogimientoAutoconsumo" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "suministroEsencial" VARCHAR NULL,
ADD COLUMN IF NOT EXISTS "cnae" VARCHAR NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'records' AND column_name = 'CNAE'
    ) THEN
        EXECUTE 'UPDATE records SET "cnae" = COALESCE("cnae", "CNAE") WHERE "cnae" IS NULL';
    END IF;
END $$;
