ALTER TABLE record_consumptions
    DROP COLUMN IF EXISTS consumoEnergiaReactivaEnVArhP1,
    DROP COLUMN IF EXISTS consumoEnergiaReactivaEnVArhP2,
    DROP COLUMN IF EXISTS consumoEnergiaReactivaEnVArhP3,
    DROP COLUMN IF EXISTS consumoEnergiaReactivaEnVArhP4,
    DROP COLUMN IF EXISTS consumoEnergiaReactivaEnVArhP5,
    DROP COLUMN IF EXISTS consumoEnergiaReactivaEnVArhP6,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaInductivaEnVArhP1 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaInductivaEnVArhP2 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaInductivaEnVArhP3 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaInductivaEnVArhP4 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaInductivaEnVArhP5 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaInductivaEnVArhP6 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaCapacitivaEnVArhP1 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaCapacitivaEnVArhP2 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaCapacitivaEnVArhP3 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaCapacitivaEnVArhP4 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaCapacitivaEnVArhP5 VARCHAR NULL,
    ADD COLUMN IF NOT EXISTS consumoEnergiaReactivaCapacitivaEnVArhP6 VARCHAR NULL;
