PS_CSV_HEADERS = [
    "codigoEmpresaDistribuidora",
    "cups",
    "nombreEmpresaDistribuidora",
    "codigoPostalPS",
    "municipioPS",
    "codigoProvinciaPS",
    "fechaAltaSuministro",
    "codigoTarifaATREnVigor",
    "codigoTensionV",
    "potenciaMaximaBIEW",
    "potenciaMaximaAPMW",
    "codigoClasificacionPS",
    "codigoDisponibilidadICP",
    "tipoPerfilConsumo",
    "valorDerechosExtensionW",
    "valorDerechosAccesoW",
    "codigoPropiedadEquipoMedida",
    "codigoPropiedadICP",
    "potenciasContratadasEnWP1",
    "potenciasContratadasEnWP2",
    "potenciasContratadasEnWP3",
    "potenciasContratadasEnWP4",
    "potenciasContratadasEnWP5",
    "potenciasContratadasEnWP6",
    "fechaUltimoMovimientoContrato",
    "fechaUltimoCambioComercializador",
    "fechaLimiteDerechosReconocidos",
    "fechaUltimaLectura",
    "informacionImpagos",
    "importeDepositoGarantiaEuros",
    "tipoIdTitular",
    "esViviendaHabitual",
    "codigoComercializadora",
    "codigoTelegestion",
    "codigoFasesEquipoMedida",
    "codigoAutoconsumo",
    "codigoTipoContrato",
    "codigoPeriodicidadFacturacion",
    "codigoBIE",
    "fechaEmisionBIE",
    "fechaCaducidadBIE",
    "codigoAPM",
    "fechaEmisionAPM",
    "fechaCaducidadAPM",
    "relacionTransformacionIntensidad",
    "CNAE",
    "codigoModoControlPotencia",
    "potenciaCGPW",
    "codigoDHEquipoDeMedida",
    "codigoAccesibilidadContador",
    "codigoPSContratable",
    "motivoEstadoNoContratable",
    "codigoTensionMedida",
    "codigoClaseExpediente",
    "codigoMotivoExpediente",
    "codigoTipoSuministro",
    "aplicacionBonoSocial",
]

CONSUMPTION_CSV_HEADERS = [
    "cups",
    "fechaInicioMesConsumo",
    "fechaFinMesConsumo",
    "codigoTarifaATR",
    "consumoEnergiaActivaEnWhP1",
    "consumoEnergiaActivaEnWhP2",
    "consumoEnergiaActivaEnWhP3",
    "consumoEnergiaActivaEnWhP4",
    "consumoEnergiaActivaEnWhP5",
    "consumoEnergiaActivaEnWhP6",
    "consumoEnergiaReactivaEnVArhP1",
    "consumoEnergiaReactivaEnVArhP2",
    "consumoEnergiaReactivaEnVArhP3",
    "consumoEnergiaReactivaEnVArhP4",
    "consumoEnergiaReactivaEnVArhP5",
    "consumoEnergiaReactivaEnVArhP6",
    "potenciaDemandadaEnWP1",
    "potenciaDemandadaEnWP2",
    "potenciaDemandadaEnWP3",
    "potenciaDemandadaEnWP4",
    "potenciaDemandadaEnWP5",
    "potenciaDemandadaEnWP6",
    "codigoDHEquipoDeMedida",
    "codigoTipoLectura",
]

CSV_HEADERS = PS_CSV_HEADERS

IMPORT_FORMAT_PS = "ps"
IMPORT_FORMAT_CONSUMPTION = "consumption"

IMPORT_FORMAT_HEADERS = {
    IMPORT_FORMAT_PS: PS_CSV_HEADERS,
    IMPORT_FORMAT_CONSUMPTION: CONSUMPTION_CSV_HEADERS,
}

ATR_TARIFF_LABELS = {
    "001": "2.0A",
    "003": "3.0A",
    "004": "2.0DHA",
    "005": "2.1A",
    "006": "2.1DHA",
    "007": "2.0DHS",
    "008": "2.1DHS",
    "011": "3.1A",
    "012": "6.1A",
    "013": "6.2",
    "014": "6.3",
    "015": "6.4",
    "016": "6.5",
    "017": "6.1B",
    "018": "2.0TD",
    "019": "3.0TD",
    "020": "6.1TD",
    "021": "6.2TD",
    "022": "6.3TD",
    "023": "6.4TD",
    "024": "3.0TDVE",
    "025": "6.1TDVE",
    "026": "6.2TDVE",
    "027": "3.0TDVE - Embarcacions",
    "028": "6.1TDVE - Embarcacions",
    "029": "6.2TDVE - Embarcacions",
}

CONSUMPTION_TABLE_FIELDS = [
    "fechaInicioMesConsumo",
    "fechaFinMesConsumo",
    "codigoTarifaATR",
    "consumoEnergiaActivaEnWhP1",
    "consumoEnergiaActivaEnWhP2",
    "consumoEnergiaActivaEnWhP3",
    "consumoEnergiaActivaEnWhP4",
    "consumoEnergiaActivaEnWhP5",
    "consumoEnergiaActivaEnWhP6",
    "consumoEnergiaReactivaEnVArhP1",
    "consumoEnergiaReactivaEnVArhP2",
    "consumoEnergiaReactivaEnVArhP3",
    "consumoEnergiaReactivaEnVArhP4",
    "consumoEnergiaReactivaEnVArhP5",
    "consumoEnergiaReactivaEnVArhP6",
    "potenciaDemandadaEnWP1",
    "potenciaDemandadaEnWP2",
    "potenciaDemandadaEnWP3",
    "potenciaDemandadaEnWP4",
    "potenciaDemandadaEnWP5",
    "potenciaDemandadaEnWP6",
    "codigoDHEquipoDeMedida",
    "codigoTipoLectura",
    "uploaded_at",
]


FIELD_LABELS_CA = {
    "codigoEmpresaDistribuidora": "Codi distribuidora",
    "cups": "CUPS",
    "nombreEmpresaDistribuidora": "Distribuidora",
    "codigoPostalPS": "Codi postal",
    "municipioPS": "Municipi",
    "codigoProvinciaPS": "Provincia",
    "fechaAltaSuministro": "Alta subministrament",
    "codigoTarifaATREnVigor": "Tarifa ATR",
    "codigoTensionV": "Tensió",
    "potenciaMaximaBIEW": "Pot. max. BIE",
    "potenciaMaximaAPMW": "Pot. max. APM",
    "codigoClasificacionPS": "Classificació PS",
    "codigoDisponibilidadICP": "Disponibilitat ICP",
    "tipoPerfilConsumo": "Perfil consum",
    "valorDerechosExtensionW": "Drets extensió",
    "valorDerechosAccesoW": "Drets accés",
    "codigoPropiedadEquipoMedida": "Propietat equip",
    "codigoPropiedadICP": "Propietat ICP",
    "potenciasContratadasEnWP1": "Potència P1",
    "potenciasContratadasEnWP2": "Potència P2",
    "potenciasContratadasEnWP3": "Potència P3",
    "potenciasContratadasEnWP4": "Potència P4",
    "potenciasContratadasEnWP5": "Potència P5",
    "potenciasContratadasEnWP6": "Potència P6",
    "fechaUltimoMovimientoContrato": "Darrer moviment",
    "fechaUltimoCambioComercializador": "Darrer canvi comer.",
    "fechaLimiteDerechosReconocidos": "Limit drets",
    "fechaUltimaLectura": "Última lectura",
    "informacionImpagos": "Impagaments",
    "importeDepositoGarantiaEuros": "Dipòsit garantia",
    "tipoIdTitular": "Tipus ID titular",
    "esViviendaHabitual": "Habitatge habitual",
    "codigoComercializadora": "Codi comercialitzadora",
    "codigoTelegestion": "Telegestió",
    "codigoFasesEquipoMedida": "Fases equip",
    "codigoAutoconsumo": "Autoconsum",
    "codigoTipoContrato": "Tipus contracte",
    "codigoPeriodicidadFacturacion": "Freq. facturació",
    "codigoBIE": "Codi BIE",
    "fechaEmisionBIE": "Emissió BIE",
    "fechaCaducidadBIE": "Caducitat BIE",
    "codigoAPM": "Codi APM",
    "fechaEmisionAPM": "Emissió APM",
    "fechaCaducidadAPM": "Caducitat APM",
    "relacionTransformacionIntensidad": "Rel. transformació",
    "CNAE": "CNAE",
    "codigoModoControlPotencia": "Control potència",
    "potenciaCGPW": "Potència CGP",
    "codigoDHEquipoDeMedida": "DH equip",
    "codigoAccesibilidadContador": "Accés comptador",
    "codigoPSContratable": "PS contractable",
    "motivoEstadoNoContratable": "Motiu no contractable",
    "codigoTensionMedida": "Tensió mesura",
    "codigoClaseExpediente": "Classe expedient",
    "codigoMotivoExpediente": "Motiu expedient",
    "codigoTipoSuministro": "Tipus subministrament",
    "aplicacionBonoSocial": "Bono social",
    "fechaInicioMesConsumo": "Inici periode",
    "fechaFinMesConsumo": "Fi periode",
    "codigoTarifaATR": "Tarifa ATR",
    "consumoEnergiaActivaEnWhP1": "Consum actiu P1",
    "consumoEnergiaActivaEnWhP2": "Consum actiu P2",
    "consumoEnergiaActivaEnWhP3": "Consum actiu P3",
    "consumoEnergiaActivaEnWhP4": "Consum actiu P4",
    "consumoEnergiaActivaEnWhP5": "Consum actiu P5",
    "consumoEnergiaActivaEnWhP6": "Consum actiu P6",
    "consumoEnergiaReactivaEnVArhP1": "Consum reactiu P1",
    "consumoEnergiaReactivaEnVArhP2": "Consum reactiu P2",
    "consumoEnergiaReactivaEnVArhP3": "Consum reactiu P3",
    "consumoEnergiaReactivaEnVArhP4": "Consum reactiu P4",
    "consumoEnergiaReactivaEnVArhP5": "Consum reactiu P5",
    "consumoEnergiaReactivaEnVArhP6": "Consum reactiu P6",
    "potenciaDemandadaEnWP1": "Potència demandada P1",
    "potenciaDemandadaEnWP2": "Potència demandada P2",
    "potenciaDemandadaEnWP3": "Potència demandada P3",
    "potenciaDemandadaEnWP4": "Potència demandada P4",
    "potenciaDemandadaEnWP5": "Potència demandada P5",
    "potenciaDemandadaEnWP6": "Potència demandada P6",
    "codigoTipoLectura": "Tipus lectura",
    "uploaded_at": "Actualitzat",
}


FIELD_GROUPS = [
    (
        "Identificació",
        [
            "codigoEmpresaDistribuidora",
            "cups",
            "nombreEmpresaDistribuidora",
            "codigoComercializadora",
            "tipoIdTitular",
            "codigoTipoSuministro",
            "CNAE",
        ],
    ),
    (
        "Ubicació",
        [
            "codigoPostalPS",
            "municipioPS",
            "codigoProvinciaPS",
        ],
    ),
    (
        "Contracte",
        [
            "fechaAltaSuministro",
            "codigoTarifaATREnVigor",
            "codigoTipoContrato",
            "codigoPeriodicidadFacturacion",
            "esViviendaHabitual",
            "codigoAutoconsumo",
            "codigoPSContratable",
            "motivoEstadoNoContratable",
            "informacionImpagos",
            "importeDepositoGarantiaEuros",
        ],
    ),
    (
        "Potències",
        [
            "potenciaMaximaBIEW",
            "potenciaMaximaAPMW",
            "potenciasContratadasEnWP1",
            "potenciasContratadasEnWP2",
            "potenciasContratadasEnWP3",
            "potenciasContratadasEnWP4",
            "potenciasContratadasEnWP5",
            "potenciasContratadasEnWP6",
            "potenciaCGPW",
        ],
    ),
    (
        "Mesura i equips",
        [
            "codigoDisponibilidadICP",
            "codigoPropiedadEquipoMedida",
            "codigoPropiedadICP",
            "codigoTelegestion",
            "codigoFasesEquipoMedida",
            "codigoModoControlPotencia",
            "codigoDHEquipoDeMedida",
            "codigoAccesibilidadContador",
            "codigoTensionV",
            "codigoTensionMedida",
            "relacionTransformacionIntensidad",
        ],
    ),
    (
        "Dates",
        [
            "uploaded_at",
            "fechaUltimoMovimientoContrato",
            "fechaUltimoCambioComercializador",
            "fechaLimiteDerechosReconocidos",
            "fechaUltimaLectura",
            "fechaEmisionBIE",
            "fechaCaducidadBIE",
            "fechaEmisionAPM",
            "fechaCaducidadAPM",
        ],
    ),
    (
        "Tècnic",
        [
            "codigoClasificacionPS",
            "tipoPerfilConsumo",
            "valorDerechosExtensionW",
            "valorDerechosAccesoW",
            "codigoBIE",
            "codigoAPM",
            "codigoClaseExpediente",
            "codigoMotivoExpediente",
            "aplicacionBonoSocial",
        ],
    ),
]
