PS_CSV_HEADERS = [
    "codigoEmpresaDistribuidora",
    "nombreEmpresaDistribuidora",
    "cups",
    "referenciaCatastralPS",
    "XPS",
    "YPS",
    "HusoPS",
    "BandaPS",
    "PaisPS",
    "codigoProvinciaPS",
    "desProvinciaPS",
    "codigoMunicipioPS",
    "desMunicipioPS",
    "PoblacionPS",
    "desPoblacionPS",
    "codigoPostalPS",
    "tipoViaPS",
    "viaPS",
    "numFincaPS",
    "duplicadorFincaPS",
    "escaleraPS",
    "pisoPS",
    "puertaPS",
    "tipoAclaradorFincaPS",
    "aclaradorFincaPS",
    "fechaAltaSuministro",
    "codigoTarifaATREnVigor",
    "codigoSegmentoCargoEnVigor",
    "codigoTensionV",
    "potenciaMaximaBIEW",
    "potenciaMaximaAPMW",
    "codigoClasificacionPS",
    "tipoControDelPotencia",
    "tipoPerfilConsumo",
    "valorDerechosExtensionW",
    "valorDerechosAccesoW",
    "codigoPropiedadEquipoMedida",
    "codigoPropiedadICP",
    "potenciasContratadasEnWP1",
    "potenciasContratadasEnWP2",
    "potenciasContratadasEnWP3",
    "potenciasContratadasEnWP4",
    "potenciasContratadasEnWP5",
    "potenciasContratadasEnWP6",
    "fechaUltimoMovimientoContrato",
    "fechaUltimoCambioComercializador",
    "cambioComercializadorEnCurso",
    "codigoComercializadorVigente",
    "fechaUltimoCambioAgregadorIndependiente",
    "cambioAgregadorIndependienteEnCurso",
    "codigoAgregadorIndependienteVigente",
    "fechaLimiteDerechosReconocidos",
    "fechaUltimaLectura",
    "suspensionSuminstroImpago",
    "tipoPersona",
    "tipoIdTitular",
    "idTitular",
    "nombreTitular",
    "apellido1Titular",
    "apellido2Titular",
    "PaisTitular",
    "codigoProvinciaTitular",
    "desProvinciaTitular",
    "codigoMunicipioTitular",
    "desMunicipioTitular",
    "PoblacionTitular",
    "desPoblacionTitular",
    "codigoPostalTitular",
    "tipoViaTitular",
    "viaTitular",
    "numFincaTitular",
    "duplicadorFincaTitular",
    "escaleraTitular",
    "pisoTitular",
    "puertaTitular",
    "tipoAclaradorFincaTitular",
    "aclaradorFincaTitular",
    "esViviendaHabitual",
    "codigoLecturaRemota",
    "codigoFasesEquipoMedida",
    "acogimientoAutoconsumo",
    "aplicacionBonoSocial",
    "suministroEsencial",
    "cnae",
    "codigoTipoContrato",
    "codigoPeriodicidadFacturacion",
    "codigoBIE",
    "fechaEmisionBIE",
    "fechaCaducidadBIE",
    "codigoAPM",
    "fechaEmisionAPM",
    "fechaCaducidadAPM",
    "relacionTransformacionIntensidad",
    "codigoModoControlPotencia",
    "potenciaCGPW",
    "codigoDHEquipoDeMedida",
    "codigoAccesibilidadContador",
    "codigoPSContratable",
    "motivoEstadoNoContratable",
    "codigoTensionMedida",
    "codigoClaseExpediente",
    "codigoMotivoExpediente",
    "codigoTipoSuministro",
]

CONSUMPTION_CSV_HEADERS = [
    "cups",
    "fechaInicioMesConsumo",
    "fechaFinMesConsumo",
    "codigoTarifaATR",
    "consumoEnergiaActivaEnWhP1",
    "consumoEnergiaActivaEnWhP2",
    "consumoEnergiaActivaEnWhP3",
    "consumoEnergiaActivaEnWhP4",
    "consumoEnergiaActivaEnWhP5",
    "consumoEnergiaActivaEnWhP6",
    "consumoEnergiaReactivaInductivaEnVArhP1",
    "consumoEnergiaReactivaInductivaEnVArhP2",
    "consumoEnergiaReactivaInductivaEnVArhP3",
    "consumoEnergiaReactivaInductivaEnVArhP4",
    "consumoEnergiaReactivaInductivaEnVArhP5",
    "consumoEnergiaReactivaInductivaEnVArhP6",
    "consumoEnergiaReactivaCapacitivaEnVArhP1",
    "consumoEnergiaReactivaCapacitivaEnVArhP2",
    "consumoEnergiaReactivaCapacitivaEnVArhP3",
    "consumoEnergiaReactivaCapacitivaEnVArhP4",
    "consumoEnergiaReactivaCapacitivaEnVArhP5",
    "consumoEnergiaReactivaCapacitivaEnVArhP6",
    "potenciaDemandadaEnWP1",
    "potenciaDemandadaEnWP2",
    "potenciaDemandadaEnWP3",
    "potenciaDemandadaEnWP4",
    "potenciaDemandadaEnWP5",
    "potenciaDemandadaEnWP6",
    "codigoDHEquipoDeMedida",
    "codigoTipoLectura",
]

AUTOCONSUMO_CSV_HEADERS = [
    "cau",
    "fechaInicioReparto",
    "cups",
    "horaCoeficienteVariableReparto",
    "coeficienteReparto",
]

CSV_HEADERS = PS_CSV_HEADERS

IMPORT_FORMAT_PS = "ps"
IMPORT_FORMAT_CONSUMPTION = "consumption"
IMPORT_FORMAT_AUTOCONSUMO = "autoconsumo"

IMPORT_FORMAT_HEADERS = {
    IMPORT_FORMAT_PS: PS_CSV_HEADERS,
    IMPORT_FORMAT_CONSUMPTION: CONSUMPTION_CSV_HEADERS,
    IMPORT_FORMAT_AUTOCONSUMO: AUTOCONSUMO_CSV_HEADERS,
}

ATR_TARIFF_LABELS = {
    "001": "2.0A",
    "003": "3.0A",
    "004": "2.0DHA",
    "005": "2.1A",
    "006": "2.1DHA",
    "007": "2.0DHS",
    "008": "2.1DHS",
    "011": "3.1A",
    "012": "6.1A",
    "013": "6.2",
    "014": "6.3",
    "015": "6.4",
    "016": "6.5",
    "017": "6.1B",
    "018": "2.0TD",
    "019": "3.0TD",
    "020": "6.1TD",
    "021": "6.2TD",
    "022": "6.3TD",
    "023": "6.4TD",
    "024": "3.0TDVE",
    "025": "6.1TDVE",
    "026": "6.2TDVE",
    "027": "3.0TDVE - Embarcacions",
    "028": "6.1TDVE - Embarcacions",
    "029": "6.2TDVE - Embarcacions",
}

CONSUMPTION_TABLE_FIELDS = [
    "fechaInicioMesConsumo",
    "fechaFinMesConsumo",
    "codigoTarifaATR",
    "consumoEnergiaActivaEnWhP1",
    "consumoEnergiaActivaEnWhP2",
    "consumoEnergiaActivaEnWhP3",
    "consumoEnergiaActivaEnWhP4",
    "consumoEnergiaActivaEnWhP5",
    "consumoEnergiaActivaEnWhP6",
    "consumoEnergiaReactivaInductivaEnVArhP1",
    "consumoEnergiaReactivaInductivaEnVArhP2",
    "consumoEnergiaReactivaInductivaEnVArhP3",
    "consumoEnergiaReactivaInductivaEnVArhP4",
    "consumoEnergiaReactivaInductivaEnVArhP5",
    "consumoEnergiaReactivaInductivaEnVArhP6",
    "consumoEnergiaReactivaCapacitivaEnVArhP1",
    "consumoEnergiaReactivaCapacitivaEnVArhP2",
    "consumoEnergiaReactivaCapacitivaEnVArhP3",
    "consumoEnergiaReactivaCapacitivaEnVArhP4",
    "consumoEnergiaReactivaCapacitivaEnVArhP5",
    "consumoEnergiaReactivaCapacitivaEnVArhP6",
    "potenciaDemandadaEnWP1",
    "potenciaDemandadaEnWP2",
    "potenciaDemandadaEnWP3",
    "potenciaDemandadaEnWP4",
    "potenciaDemandadaEnWP5",
    "potenciaDemandadaEnWP6",
    "codigoDHEquipoDeMedida",
    "codigoTipoLectura",
    "uploaded_at",
]

AUTOCONSUMO_TABLE_FIELDS = [
    "cau",
    "fechaInicioReparto",
    "cups",
    "horaCoeficienteVariableReparto",
    "coeficienteReparto",
    "uploaded_at",
]


FIELD_LABELS_CA = {
    "codigoEmpresaDistribuidora": "Codi distribuidora",
    "nombreEmpresaDistribuidora": "Distribuidora",
    "cups": "CUPS",
    "referenciaCatastralPS": "Referència cadastral",
    "XPS": "Coordenada X",
    "YPS": "Coordenada Y",
    "HusoPS": "Huso",
    "BandaPS": "Banda",
    "PaisPS": "País",
    "codigoProvinciaPS": "Codi província PS",
    "desProvinciaPS": "Província PS",
    "codigoMunicipioPS": "Codi municipi PS",
    "desMunicipioPS": "Municipi PS",
    "PoblacionPS": "Codi població PS",
    "desPoblacionPS": "Població PS",
    "codigoPostalPS": "Codi postal",
    "tipoViaPS": "Tipus de via PS",
    "viaPS": "Via PS",
    "numFincaPS": "Número finca PS",
    "duplicadorFincaPS": "Duplicador finca PS",
    "escaleraPS": "Escala PS",
    "pisoPS": "Pis PS",
    "puertaPS": "Porta PS",
    "tipoAclaradorFincaPS": "Tipus aclaridor finca PS",
    "aclaradorFincaPS": "Aclaridor finca PS",
    "fechaAltaSuministro": "Alta subministrament",
    "codigoTarifaATREnVigor": "Tarifa ATR",
    "codigoSegmentoCargoEnVigor": "Segment càrrec vigent",
    "codigoTensionV": "Tensió",
    "potenciaMaximaBIEW": "Pot. max. BIE",
    "potenciaMaximaAPMW": "Pot. max. APM",
    "codigoClasificacionPS": "Classificació PS",
    "tipoControDelPotencia": "Tipus control potència",
    "tipoPerfilConsumo": "Perfil consum",
    "valorDerechosExtensionW": "Drets extensió",
    "valorDerechosAccesoW": "Drets accés",
    "codigoPropiedadEquipoMedida": "Propietat equip",
    "codigoPropiedadICP": "Propietat ICP",
    "potenciasContratadasEnWP1": "Potència P1",
    "potenciasContratadasEnWP2": "Potència P2",
    "potenciasContratadasEnWP3": "Potència P3",
    "potenciasContratadasEnWP4": "Potència P4",
    "potenciasContratadasEnWP5": "Potència P5",
    "potenciasContratadasEnWP6": "Potència P6",
    "fechaUltimoMovimientoContrato": "Darrer moviment",
    "fechaUltimoCambioComercializador": "Darrer canvi comer.",
    "cambioComercializadorEnCurso": "Canvi comercialitzador en curs",
    "codigoComercializadorVigente": "Codi comercialitzador vigent",
    "fechaUltimoCambioAgregadorIndependiente": "Darrer canvi agregador ind.",
    "cambioAgregadorIndependienteEnCurso": "Canvi agregador ind. en curs",
    "codigoAgregadorIndependienteVigente": "Codi agregador ind. vigent",
    "fechaLimiteDerechosReconocidos": "Limit drets",
    "fechaUltimaLectura": "Última lectura",
    "suspensionSuminstroImpago": "Suspensió submin. per impagament",
    "tipoPersona": "Tipus persona",
    "tipoIdTitular": "Tipus ID titular",
    "idTitular": "ID titular",
    "nombreTitular": "Nom titular",
    "apellido1Titular": "1r cognom titular",
    "apellido2Titular": "2n cognom titular",
    "PaisTitular": "País titular",
    "codigoProvinciaTitular": "Codi província titular",
    "desProvinciaTitular": "Província titular",
    "codigoMunicipioTitular": "Codi municipi titular",
    "desMunicipioTitular": "Municipi titular",
    "PoblacionTitular": "Codi població titular",
    "desPoblacionTitular": "Població titular",
    "codigoPostalTitular": "Codi postal titular",
    "tipoViaTitular": "Tipus de via titular",
    "viaTitular": "Via titular",
    "numFincaTitular": "Número finca titular",
    "duplicadorFincaTitular": "Duplicador finca titular",
    "escaleraTitular": "Escala titular",
    "pisoTitular": "Pis titular",
    "puertaTitular": "Porta titular",
    "tipoAclaradorFincaTitular": "Tipus aclaridor finca titular",
    "aclaradorFincaTitular": "Aclaridor finca titular",
    "esViviendaHabitual": "Habitatge habitual",
    "codigoLecturaRemota": "Lectura remota",
    "codigoFasesEquipoMedida": "Fases equip",
    "acogimientoAutoconsumo": "Acolliment autoconsum",
    "aplicacionBonoSocial": "Bono social",
    "suministroEsencial": "Subministrament essencial",
    "cnae": "CNAE",
    "codigoTipoContrato": "Tipus contracte",
    "codigoPeriodicidadFacturacion": "Freq. facturació",
    "codigoBIE": "Codi BIE",
    "fechaEmisionBIE": "Emissió BIE",
    "fechaCaducidadBIE": "Caducitat BIE",
    "codigoAPM": "Codi APM",
    "fechaEmisionAPM": "Emissió APM",
    "fechaCaducidadAPM": "Caducitat APM",
    "relacionTransformacionIntensidad": "Rel. transformació",
    "codigoModoControlPotencia": "Control potència",
    "potenciaCGPW": "Potència CGP",
    "codigoDHEquipoDeMedida": "DH equip",
    "codigoAccesibilidadContador": "Accés comptador",
    "codigoPSContratable": "PS contractable",
    "motivoEstadoNoContratable": "Motiu no contractable",
    "codigoTensionMedida": "Tensió mesura",
    "codigoClaseExpediente": "Classe expedient",
    "codigoMotivoExpediente": "Motiu expedient",
    "codigoTipoSuministro": "Tipus subministrament",
    "aplicacionBonoSocial": "Bono social",
    "fechaInicioMesConsumo": "Inici periode",
    "fechaFinMesConsumo": "Fi periode",
    "codigoTarifaATR": "Tarifa ATR",
    "consumoEnergiaActivaEnWhP1": "Consum actiu P1",
    "consumoEnergiaActivaEnWhP2": "Consum actiu P2",
    "consumoEnergiaActivaEnWhP3": "Consum actiu P3",
    "consumoEnergiaActivaEnWhP4": "Consum actiu P4",
    "consumoEnergiaActivaEnWhP5": "Consum actiu P5",
    "consumoEnergiaActivaEnWhP6": "Consum actiu P6",
    "consumoEnergiaReactivaInductivaEnVArhP1": "Consum reactiu inductiu P1",
    "consumoEnergiaReactivaInductivaEnVArhP2": "Consum reactiu inductiu P2",
    "consumoEnergiaReactivaInductivaEnVArhP3": "Consum reactiu inductiu P3",
    "consumoEnergiaReactivaInductivaEnVArhP4": "Consum reactiu inductiu P4",
    "consumoEnergiaReactivaInductivaEnVArhP5": "Consum reactiu inductiu P5",
    "consumoEnergiaReactivaInductivaEnVArhP6": "Consum reactiu inductiu P6",
    "consumoEnergiaReactivaCapacitivaEnVArhP1": "Consum reactiu capacitiu P1",
    "consumoEnergiaReactivaCapacitivaEnVArhP2": "Consum reactiu capacitiu P2",
    "consumoEnergiaReactivaCapacitivaEnVArhP3": "Consum reactiu capacitiu P3",
    "consumoEnergiaReactivaCapacitivaEnVArhP4": "Consum reactiu capacitiu P4",
    "consumoEnergiaReactivaCapacitivaEnVArhP5": "Consum reactiu capacitiu P5",
    "consumoEnergiaReactivaCapacitivaEnVArhP6": "Consum reactiu capacitiu P6",
    "potenciaDemandadaEnWP1": "Potència demandada P1",
    "potenciaDemandadaEnWP2": "Potència demandada P2",
    "potenciaDemandadaEnWP3": "Potència demandada P3",
    "potenciaDemandadaEnWP4": "Potència demandada P4",
    "potenciaDemandadaEnWP5": "Potència demandada P5",
    "potenciaDemandadaEnWP6": "Potència demandada P6",
    "codigoTipoLectura": "Tipus lectura",
    "uploaded_at": "Actualitzat",
    "cau": "CAU",
    "fechaInicioReparto": "Reparto start",
    "horaCoeficienteVariableReparto": "Variable coefficient hour",
    "coeficienteReparto": "Reparto coefficient",
}


FIELD_GROUPS = [
    (
        "Identificació",
        [
            "codigoEmpresaDistribuidora",
            "nombreEmpresaDistribuidora",
            "cups",
            "tipoPersona",
            "tipoIdTitular",
            "idTitular",
            "nombreTitular",
            "apellido1Titular",
            "apellido2Titular",
            "codigoTipoSuministro",
            "cnae",
        ],
    ),
    (
        "Ubicació PS",
        [
            "referenciaCatastralPS",
            "PaisPS",
            "codigoProvinciaPS",
            "desProvinciaPS",
            "codigoMunicipioPS",
            "desMunicipioPS",
            "PoblacionPS",
            "desPoblacionPS",
            "codigoPostalPS",
            "tipoViaPS",
            "viaPS",
            "numFincaPS",
            "duplicadorFincaPS",
            "escaleraPS",
            "pisoPS",
            "puertaPS",
            "tipoAclaradorFincaPS",
            "aclaradorFincaPS",
            "XPS",
            "YPS",
            "HusoPS",
            "BandaPS",
        ],
    ),
    (
        "Contracte",
        [
            "fechaAltaSuministro",
            "codigoTarifaATREnVigor",
            "codigoSegmentoCargoEnVigor",
            "codigoTipoContrato",
            "codigoPeriodicidadFacturacion",
            "codigoComercializadorVigente",
            "cambioComercializadorEnCurso",
            "codigoAgregadorIndependienteVigente",
            "cambioAgregadorIndependienteEnCurso",
            "esViviendaHabitual",
            "acogimientoAutoconsumo",
            "aplicacionBonoSocial",
            "suministroEsencial",
            "codigoPSContratable",
            "motivoEstadoNoContratable",
            "suspensionSuminstroImpago",
        ],
    ),
    (
        "Potències",
        [
            "potenciaMaximaBIEW",
            "potenciaMaximaAPMW",
            "potenciasContratadasEnWP1",
            "potenciasContratadasEnWP2",
            "potenciasContratadasEnWP3",
            "potenciasContratadasEnWP4",
            "potenciasContratadasEnWP5",
            "potenciasContratadasEnWP6",
            "potenciaCGPW",
        ],
    ),
    (
        "Mesura i equips",
        [
            "tipoControDelPotencia",
            "codigoPropiedadEquipoMedida",
            "codigoPropiedadICP",
            "codigoLecturaRemota",
            "codigoFasesEquipoMedida",
            "codigoModoControlPotencia",
            "codigoDHEquipoDeMedida",
            "codigoAccesibilidadContador",
            "codigoTensionV",
            "codigoTensionMedida",
            "relacionTransformacionIntensidad",
        ],
    ),
    (
        "Dates",
        [
            "uploaded_at",
            "fechaUltimoMovimientoContrato",
            "fechaUltimoCambioComercializador",
            "fechaUltimoCambioAgregadorIndependiente",
            "fechaLimiteDerechosReconocidos",
            "fechaUltimaLectura",
            "fechaEmisionBIE",
            "fechaCaducidadBIE",
            "fechaEmisionAPM",
            "fechaCaducidadAPM",
        ],
    ),
    (
        "Tècnic",
        [
            "codigoClasificacionPS",
            "tipoPerfilConsumo",
            "valorDerechosExtensionW",
            "valorDerechosAccesoW",
            "codigoBIE",
            "codigoAPM",
            "codigoClaseExpediente",
            "codigoMotivoExpediente",
        ],
    ),
    (
        "Titular",
        [
            "PaisTitular",
            "codigoProvinciaTitular",
            "desProvinciaTitular",
            "codigoMunicipioTitular",
            "desMunicipioTitular",
            "PoblacionTitular",
            "desPoblacionTitular",
            "codigoPostalTitular",
            "tipoViaTitular",
            "viaTitular",
            "numFincaTitular",
            "duplicadorFincaTitular",
            "escaleraTitular",
            "pisoTitular",
            "puertaTitular",
            "tipoAclaradorFincaTitular",
            "aclaradorFincaTitular",
        ],
    ),
]
